# Generated by Django 2.2.3 on 2019-08-01 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('last_change', models.DateTimeField(blank=True, verbose_name='last_change')),
                ('expired_date', models.DateTimeField(verbose_name='expired')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, verbose_name='header')),
            ],
        ),
        migrations.AlterField(
            model_name='reseller',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last_name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('telephone', models.CharField(blank=True, max_length=30, unique=True, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Card')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='packets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Packet'),
        ),
        migrations.AddField(
            model_name='card',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
