# Generated by Django 2.2.3 on 2019-08-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190801_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='last_change'),
        ),
    ]
