# Generated by Django 2.2.3 on 2019-08-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190801_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='rrr',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='rrr'),
        ),
    ]
