# Generated by Django 2.2.3 on 2019-08-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190801_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='cards',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='main.Card'),
        ),
    ]
