# Generated by Django 2.2.3 on 2019-08-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190801_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='cards',
        ),
    ]
