# Generated by Django 2.2.3 on 2019-08-01 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_subscriber_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Subscriber'),
        ),
    ]
