# Generated by Django 2.2.3 on 2019-08-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_card_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telephone'),
        ),
    ]
