# Generated by Django 2.2.3 on 2019-08-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190801_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='packets',
            new_name='packet',
        ),
    ]
