# Generated by Django 2.2.3 on 2019-08-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190801_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='price_card',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
