# Generated by Django 2.2.3 on 2019-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190801_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='rrr',
            field=models.CharField(blank=True, max_length=3, verbose_name='rrr'),
        ),
    ]
