# Generated by Django 2.2.3 on 2019-08-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190801_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='packet',
        ),
        migrations.AlterField(
            model_name='reseller',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
