# Generated by Django 2.2.3 on 2019-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190801_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activated'),
        ),
    ]
