# Generated by Django 2.2.3 on 2019-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190805_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='age_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age limit'),
        ),
        migrations.AddField(
            model_name='packet',
            name='tariff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tariff of one period'),
        ),
        migrations.AddField(
            model_name='reseller',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activated'),
        ),
    ]
