# Generated by Django 2.2.3 on 2019-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190805_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
