# Generated by Django 2.2.3 on 2019-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190805_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
