# Generated by Django 2.2.3 on 2019-08-05 14:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190805_1413'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reseller',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
