# Generated by Django 2.2.3 on 2019-08-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190805_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='packet',
        ),
    ]
