# Generated by Django 2.2.3 on 2019-08-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_card_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Card'),
        ),
    ]
