# Generated by Django 2.2.3 on 2019-08-05 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_packet_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='reseller',
            field=models.ForeignKey(default=main.models.get_admin, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
