# Generated by Django 2.2.3 on 2019-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190806_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expired_date',
            field=models.DateTimeField(verbose_name='Expired date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Last_change'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('E', 'Expired')], max_length=10, verbose_name='Status'),
        ),
    ]
