# Generated by Django 2.2.3 on 2019-08-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190806_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, verbose_name='Number')),
                ('name', models.CharField(max_length=20, verbose_name='Bouquet')),
                ('age_limit', models.IntegerField(verbose_name='Age limit')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Packet')),
            ],
        ),
    ]
