# Generated by Django 2.2.3 on 2019-08-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_bouquet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Packet'),
        ),
    ]
