# Generated by Django 2.2.3 on 2019-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190807_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Number'),
        ),
    ]
