# Generated by Django 2.2.3 on 2019-08-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190807_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='score',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='score',
        ),
        migrations.AddField(
            model_name='reseller',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bouquets', to='main.Packet'),
        ),
    ]
