# Generated by Django 2.2.3 on 2019-08-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190807_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='main.Subscriber'),
        ),
    ]
