# Generated by Django 2.2.3 on 2019-08-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190807_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='reseller',
            field=models.ForeignKey(default=main.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Active', 'A'), ('Inactive', 'I'), ('Expired', 'E')], max_length=10, verbose_name='Status'),
        ),
    ]
