# Generated by Django 2.2.3 on 2019-08-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190808_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expired date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Active', 'A'), ('Inactive', 'I'), ('Expired', 'E')], default='A', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packets', to='main.Card'),
        ),
    ]
