# Generated by Django 2.2.3 on 2019-08-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190808_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='main.Card'),
        ),
    ]
