# Generated by Django 2.2.3 on 2019-08-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190808_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='package',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='packages',
            field=models.ManyToManyField(related_name='bouquets', to='main.Packet'),
        ),
    ]
