# Generated by Django 2.2.3 on 2019-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190808_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='tariff',
            field=models.IntegerField(default=0, verbose_name='Tariff of one period'),
        ),
    ]
