import Vue from 'vue'
import './plugins/vuetify'

import App from './App.vue'
import router from './router'
import store from './store/store'
import 'material-icons'
import VueApexCharts from 'vue-apexcharts'
import VueSession from 'vue-session'

Vue.use(VueSession)
Vue.config.productionTip = false
Vue.use(VueApexCharts)
Vue.component('apexchart', VueApexCharts)
Vue.prototype.$hostname = 'http://157.230.98.28';
window.$languages = [];
window.$currentLanguage = '';
// Vue.prototype.$hostname = 'http://192.168.31.237:8000';
import VueTranslate from 'vue-translate-plugin';

Vue.use(VueTranslate);

Vue.locales({
    arabian: {
        'Cards': 'Карточки',
        'Subscribers': 'Подписчики',
        'Menu': 'Меню',
        'Dashboard': 'Дэшборд',
        'Packages': 'Пакеты',
        'Resellers': 'Реселлеры',
        'Activation': 'Активация',
        'Reports': 'Отчеты',
        'Logout': 'Выход',
        'Settings': 'Настройки',
        'Save': 'Сохранить',
        'Payment': 'Оплата',
        'Choose': 'Выберите',
        'Currency': 'Валюта',
        'Payment period': 'Период оплаты',
        'Quantity (of payment period)': 'Колличкство (периодов оплаты)',
        'Server preferences:': 'Настройки сервера:',
        'Cards prefix': 'Префикс карты',
        'Max cards': 'Максимум карт',
        'Server ip': 'Ip серверв',
        'Server port': 'Порт сервера',
        'Bouquets': 'Букеты',
        'Synchronization': 'Синхронизация',
        'Periods quantity': 'Кол-во периодов',
        'Synchronization at:': 'Синхронизация в:',
        'Period': 'Период',
        'New synchronization periods:': 'Новые периоды синхронизации',
        'Prepayment': 'Предоплата',
        'Months': 'Месяцы',
        'Search': 'Поиск',
        'Detail': 'Детали',
        'Edit': 'Редкатировать',
        'User Profile': 'Профиль пользователя',
        'First name*': 'Имя',
        'Last name*': 'Фамилия',
        'Email*': 'Email*',
        'Address': 'Адрес',
        'Phone*': 'Телефон',
        '*indicates required field': '*обязательно',
        'Close': 'Закрыть',
        'Full name': 'Фио',
        'Email': 'Email',
        'Balance': 'Баланс',
        'Action': 'Действия',
        'Details': 'Детали',
        'Name': 'Имя',
        'Cards price': 'Цена карточек',
        'Phone': 'Телефон',
        'Reseller': 'Реселлер',
        'Logs': 'Логи',
        'Remove': 'Удалить',
        'Available cards': 'Доступные карточки',
        'Add': 'Добавить',
        'Label': 'Лейбл',
        'Price': 'Цена',
        'Date': 'Дата',
        'Header': 'Заголовок',
        'Delete': 'Удалить',
        'First name': 'Имя',
        'Last name': 'Фамилия',
        'Card ID': 'Id карты',
        'Card Label': 'Лейбл карты',
        'Issued': 'Создано',
        'Edited': 'Отредактировано',
        'Expired': 'Истекает',
        'Status': 'Статус',
        'Expired date': 'Дата окончания',
        'Periods': 'Периоды',
        'Last change': 'Последнее изменение',
        'Created at': 'Создан в',
        'This package will be removed on the next transaction.': 'Будет удален',
        'Remove now': 'Удалить сейчас',
        'Remove later': 'Удлаить позже',
        'Available packages': 'Доступные пакеты',
        'This package will be added in the next transaction.': 'Будет добавлен',
        'Add now': 'Добавить сейчас',
        'Add later': 'Добавить позже',
        'Tariff': 'Тариф',
        'Subscriber': 'Подписчик',
        'Package': 'Пакет',
        'Header*': '',
        'Tariff*': '',
        'Package ID': 'Id пакета',
        'Age limit': 'Ограничение по возрасту',
        'Login': 'Вход',
        'Username': 'Имя пользователя',
        'Password': 'Пароль',
        'Register now!': 'Зарегесрироваться сейчас!',
        'Forgot Password?': 'Забыли пароль?',
        'Submit': 'Отправить',
        'Please check your email': 'Проверь почту',
        'to verify your account': 'чтобы подтвердить',
        'Repeat password': 'Повторите пароль',
        'Sign-up': 'Зарегаться',
        'Register': 'Регистрация',
        'Already heave an account?': 'Уже есть аккаунт',
        'From': 'От',
        'To': 'К',
        'Finance': 'Финансы',
        'Reseller cards': 'Карточки реселлера',
        'Total': 'Всего',
        'Send': 'Отправить',
        'Are you sure you want to delete?': 'Вы уверены что хотите удлаить ?',
        'This action cannot be undone': 'Это дейтсвие невозможно отменить',
        'Comment': 'Комментарий',
        'Zone': 'Зона',
        'Card price': 'Цена карточки',
        'Credit': 'Кредит',
        'Status verification': 'Подтверждение стаутса',
        'Permissions': 'Права',
        'surname': 'Фамилия',
        'subscribers': 'подписчики',
        'cards of subscribers': 'карточки подписичка',
        'finance': 'финансы',
        'cards': 'карточки',
        'Total cards': 'Всего карточек',
        'Rows per page': 'Строк на страницу',
        'Elements': 'Элементы',
        'total': 'всего',
        'No data available': 'Нет данных',
        'Required.': 'Обязательно.',
        'Max 100': 'Макс 100',
        'Max 128': 'Макс 128',
        'Max 100 characters': 'Макс 100 символов',
        'Min 1 Max 8': 'Мин 1 Макс 8',
        'Min 1 Max 128': 'Мин 1 Макс 128',
        'Invalid number.': 'Неправильное число',
        'Min 0 Max 99999': 'Мин 0 Макс 99999',
        'Min 0 Max 100000': 'Мин 0 Макс 100000',
        'Invalid id address': 'Неверный ip адрес',
        'Min 0 Max 65535': 'Мин 0 Макс 65535',
        'Min 1 and Max 2147483647': 'Мин 1 Макс 2147483647',
        'Max 2147483647': 'Макс 2147483647',
        'Username between the 4 - 150 characters': 'Имя пользователя от 4 до 150 символов',
        'Min 8 characters': 'Мин 8 символов',
        'Invalid e-mail.': 'Неверный e-mail',
        'Passwords do not match': 'Пароли не совпадают',
        'Min 0 Max 999': 'Мин 0 Макс 999',
        'Only admins can have prefix "000"': 'Только у адмнов может быть карточка с префиксом 000',
        'Connection error': 'Ошибка соединения',
        'Fill the form correctly': 'Заполните форму корректно',
        'Incorrect data': 'Неверные данные',
        'Oops... Something went wrong': 'Упс... Что-то пошло не так',
        'Settings changed!': 'Настройки изменены',
        'Fill the number of bouquets correctly': 'Заполните кол-во букетов правильно',
        'Bouquets updated!': 'Букеты обновлены',
        'Fill the periods correctly': 'Заполните периоды корректно',
        'Periods updated!': "Периоды обновлены",
        'Card created!': 'Карточка созданы',
        'Cards were created!': 'Карточки были созданы',
        'Status changed!': 'Статус изменен',
        'Period changed!': 'Период изменен',
        'The subscriber does not have enough funds': "У подписчика недостаточно средств",
        '3 days passed': "3 дня вышло",
        "Registration successful": 'Регистрация успешна',
        'Balance too low': "Бланс слишком мал",
        'Tariff changed!': 'Тариф изменен',
        'Successful': 'Успешно',
        'Balance changed!': 'Баланс изменен',
        'Cards were applied!': 'Карточки были применены',
        'Incorrect range': 'Некорректый диапазон',
        'Permissions changed!': 'Права изменены',
        'Subscriber created!': 'Подписчик создан',


    }
});

Vue.use(VueTranslate);
new Vue({
    router,
    store,
    render: h => h(App)
}).$mount('#app');
